---
apiVersion: v1
kind: Service
metadata:
  name: uptime-robot
  namespace: kube-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: status.hacksm.net
spec:
  type: ExternalName
  externalName: stats.uptimerobot.com
