apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: rr5
  namespace: mc
spec:
  chart:
    git: git@github.com:HRZNStudio/playhrzn-k8s
    ref: master
    path: charts/minecraft
  values:
    # ref: charts/minecraft/values.yaml
    resources:
      requests:
        memory: 8Gi
        cpu: "1"
    livenessProbe:
      initialDelaySeconds: 300
      periodSeconds: 10
    readinessProbe:
      initialDelaySeconds: 300
      periodSeconds: 10
    minecraftServer:
      eula: "TRUE"
      version: "1.12.2"
      type: "FORGE"
      forgeVersion: "14.23.5.2847"
      motd: "RR5 Staging - K8s"
      maxtickTime: -1
      memory: 8G
      annotations:
        external-dns.alpha.kubernetes.io/hostname: rr5.mc.playhrzn.com
      rcon:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/hostname: rr5-rcon.mc.playhrzn.com
      rconWebAdmin:
        enabled: true 
        image: docker.io/cwlf/rcon@sha256
        imageTag: e6d0d325f9686c00f8b4b50afd9ef7a03a5bf0c305e7567db008d8679163c6b1
        websocketUrlSsl: "wss://rr5-rwa.mc.playhrzn.com:4327"
        serviceType: NodePort
      cloudCommander:
        enabled: true
        port: 80
        imageTag: 14.3.10-alpine
        serviceType: NodePort
    extraEnv:
      GENERIC_PACK: "https://cdn.hrzn.studio/rr5-server-staging.zip"
      GENERIC_PACK_STRIP_DIRS: "0"
      OVERRIDE_SERVER_PROPERTIES: "1"
    persistence:
      dataDir:
        enabled: true
        Size: 5Gi