apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: rr5
  namespace: mc
spec:
  chart:
    git: https://github.com/hrznstudio/mc-helm-chart
    ref: master
    path: /
  values:
    # ref: https://github.com/hrznstudio/mc-helm-chart/blob/master/values.yaml
    resources:
      requests:
        memory: 8Gi
        cpu: "1"
    livenessProbe:
      initialDelaySeconds: 300
      periodSeconds: 10
    readinessProbe:
      initialDelaySeconds: 300
      periodSeconds: 10
    minecraftServer:
      eula: "TRUE"
      version: "1.12.2"
      type: "FORGE"
      forgeVersion: "14.23.5.2847"
      motd: "RR5 Staging - K8s"
      maxtickTime: -1
      memory: 8G
      annotations:
        external-dns.alpha.kubernetes.io/hostname: rr5.mc.playhrzn.com
      rcon:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/hostname: rr5-rcon.mc.playhrzn.com
      cloudCommander:
        enabled: true
        port: 80
        serviceType: NodePort
    extraEnv:
      GENERIC_PACK: "https://cdn.hrzn.studio/rr5-server-staging.zip"
      GENERIC_PACK_STRIP_DIRS: "0"
      OVERRIDE_SERVER_PROPERTIES: "1"
