---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: test
  namespace: mc
spec:
  releaseName: test
  chart:
    git: git@github.com:HRZNStudio/playhrzn-k8s
    ref: master
    path: charts/minecraft
  values:
    domain: playhrzn.com
    minecraftServer:
      image: itzg/minecraft-server:latest@sha256:5e5f5ee7f1ac278384417f03553d4e1fbf5b259d97c203992a2580514d4e7404
      eula: "TRUE"
      version: "1.14.4"
      type: "PAPER"
