---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: test
  namespace: mc
spec:
  releaseName: test
  chart:
    git: git@github.com:HRZNStudio/playhrzn-k8s
    ref: master
    path: charts/minecraft
  values:
    domain: playhrzn.com
    minecraftServer:
      image: itzg/minecraft-server:latest@sha256:dbaf3a2bc3d6ef40e703e35420d66a5c3fb22e4dad05d5edcc516cdecb7e97e8
      eula: "TRUE"
      version: "1.14.4"
      type: "PAPER"
