---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: test
  namespace: mc
spec:
  releaseName: test
  chart:
    git: git@github.com:HRZNStudio/playhrzn-k8s
    ref: master
    path: charts/minecraft
  values:
    domain: playhrzn.com
    minecraftServer:
      image: itzg/minecraft-server:latest@sha256:8396ada0c3a1f67caf337a663988f7d4b0422f2e70daa4c4685a7bd4674c7ad5
      eula: "TRUE"
      version: "1.14.4"
      type: "PAPER"
