---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: yogs
  namespace: mc
spec:
  chart:
    git: git@github.com:HRZNStudio/playhrzn-k8s
    ref: master
    path: charts/minecraft
  values:
    # ref: charts/minecraft/values.yaml
    affinity:
      podAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - mc-yogs-minecraft
                - key: app
                  operator: NotIn
                  values:
                    - mc-rr5-minecraft
            topologyKey: "kubernetes.io/hostname"
    resources:
      requests:
        memory: 8Gi
        cpu: "1"
    livenessProbe:
      initialDelaySeconds: 300
      periodSeconds: 10
    readinessProbe:
      initialDelaySeconds: 300
      periodSeconds: 10
    minecraftServer:
      image: itzg/minecraft-server:openj9@sha256:e0c0fe5caa397a5c3cb7b473555c5faca5d422abb3abec9b52053e7cf952f45f
      eula: "TRUE"
      version: "1.12.2"
      type: "FORGE"
      forgeVersion: "14.23.5.2847"
      maxWorldSize: 29999984
      maxtickTime: -1
      memory: 8G
      annotations:
        external-dns.alpha.kubernetes.io/hostname: yogs.mc.playhrzn.com
      rcon:
        enabled: true
        serviceType: NodePort
      rconWebAdmin:
        enabled: true
        image: docker.io/cwlf/rcon@sha256:e6d0d325f9686c00f8b4b50afd9ef7a03a5bf0c305e7567db008d8679163c6b1
        websocketUrlSsl: "wss://yogs-rwa-ws.mc.playhrzn.com"
        serviceType: NodePort
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "nginx"
        webIngress:
          hostname: yogs-rwa.mc.playhrzn.com
          annotations:
            forecastle.stakater.com/expose: "true"
            external-dns.alpha.kubernetes.io/hostname: yogs-rwa.mc.playhrzn.com
        websocketIngress:
          hostname: yogs-rwa-ws.mc.playhrzn.com
          annotations:
            external-dns.alpha.kubernetes.io/hostname: yogs-rwa-ws.mc.playhrzn.com
      cloudCommander:
        enabled: true
        image: coderaiser/cloudcmd:14.5.1-alpine@sha256:4d78e27eeb4393ef330b8121c84b7a78b499ee6d364bea3f697523165e292d38
        serviceType: NodePort
        ingress:
          enabled: true
          hostname: yogs-files.mc.playhrzn.com
          annotations:
            kubernetes.io/ingress.class: "nginx"
            forecastle.stakater.com/expose: "true"
            external-dns.alpha.kubernetes.io/hostname: yogs-files.mc.playhrzn.com
    extraEnv:
      GENERIC_PACK: "https://cdn.hrzn.studio/yogs-server-staging.zip"
      GENERIC_PACK_STRIP_DIRS: "0"
      OVERRIDE_SERVER_PROPERTIES: "1"
    persistence:
      dataDir:
        enabled: true
        Size: 5Gi
      storageClass: ebs-sc
      volumeName: pvc-d0d01d32-bf54-4339-8272-80190ecd186e
