---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: yogs
  namespace: mc
spec:
  releaseName: yogs
  chart:
    git: git@github.com:HRZNStudio/playhrzn-k8s
    ref: master
    path: charts/minecraft
  values:
    # ref: charts/minecraft/values.yaml
    domain: playhrzn.com
    minecraftServer:
      image: itzg/minecraft-server:latest@sha256:dbaf3a2bc3d6ef40e703e35420d66a5c3fb22e4dad05d5edcc516cdecb7e97e8
      eula: "TRUE"
      version: "1.12.2"
      type: "FORGE"
      forgeVersion: "14.23.5.2847"
      maxtickTime: -1
      memory: 8G
      rconWebAdmin:
        image: cwlf/rcon:latest@sha256:e6d0d325f9686c00f8b4b50afd9ef7a03a5bf0c305e7567db008d8679163c6b1
        websocketUrlSsl: "wss://yogs-rwa-ws.playhrzn.com"
        webIngress:
          hostname: yogs-rwa.playhrzn.com
          annotations:
            ingress.pomerium.io/allowed_domains: '["chipwolf.uk", "hrznstudio.com"]'
            forecastle.stakater.com/expose: "true"
            forecastle.stakater.com/icon: https://brainfoolong.github.io/rcon-web-admin/images/logo.png
            forecastle.stakater.com/appName: "RCON Web Admin"
            forecastle.stakater.com/group: "yogs"
        websocketIngress:
          hostname: yogs-rwa-ws.playhrzn.com
          annotations:
            kubernetes.io/ingress.class: "nginx"
      cloudCommander:
        image: coderaiser/cloudcmd:14.9.2-alpine@sha256:de15a93bb621252adc3c35e1dbd03f2e6d157620fb310abc6bac9e8e4b9fee21
        ingress:
          hostname: yogs-files.playhrzn.com
          annotations:
            ingress.pomerium.io/allowed_domains: '["chipwolf.uk", "hrznstudio.com"]'
            forecastle.stakater.com/expose: "true"
            forecastle.stakater.com/icon: https://cloudcmd.io/img/logo/cloudcmd.png
            forecastle.stakater.com/appName: "File Manager"
            forecastle.stakater.com/group: "yogs"
    extraEnv:
      GENERIC_PACK: "https://cdn.hrzn.studio/yogs-server-staging.zip"
      GENERIC_PACK_STRIP_DIRS: "0"
      OVERRIDE_SERVER_PROPERTIES: "1"
      USE_AIKAR_FLAGS: "1"
    persistence:
      volumeName: pvc-d0d01d32-bf54-4339-8272-80190ecd186e
---
apiVersion: "autoscaling.k8s.io/v1beta2"
kind: VerticalPodAutoscaler
metadata:
  name: yogs-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: mc-yogs-minecraft
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 100m
          memory: 4608Mi
        maxAllowed:
          cpu: 2
          memory: 8Gi
        controlledResources: ["cpu", "memory"]
