---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: yogs
  namespace: mc
spec:
  chart:
    git: git@github.com:HRZNStudio/playhrzn-k8s
    ref: master
    path: charts/minecraft
  values:
    # ref: charts/minecraft/values.yaml
    affinity:
      podAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - mc-yogs-minecraft
            topologyKey: "kubernetes.io/hostname"
    livenessProbe:
      initialDelaySeconds: 300
      periodSeconds: 10
    readinessProbe:
      initialDelaySeconds: 300
      periodSeconds: 10
    minecraftServer:
      image: itzg/minecraft-server:latest@sha256:a8973502f279a86c75e366a4d6837142c82e495053bf4b18f3959eb45dec07c2
      eula: "TRUE"
      version: "1.12.2"
      type: "FORGE"
      forgeVersion: "14.23.5.2847"
      maxWorldSize: 29999984
      maxtickTime: -1
      memory: 8G
      annotations:
        external-dns.alpha.kubernetes.io/hostname: yogs.mc.playhrzn.com
      rcon:
        enabled: true
        serviceType: NodePort
      rconWebAdmin:
        enabled: true
        image: cwlf/rcon:latest@sha256:e6d0d325f9686c00f8b4b50afd9ef7a03a5bf0c305e7567db008d8679163c6b1
        websocketUrlSsl: "wss://yogs-rwa-ws.mc.playhrzn.com"
        serviceType: NodePort
        ingress:
          enabled: true
        webIngress:
          hostname: yogs-rwa.mc.playhrzn.com
          annotations:
            ingress.pomerium.io/allowed_domains: '["chipwolf.uk", "hrznstudio.com"]'
            forecastle.stakater.com/expose: "true"
            forecastle.stakater.com/icon: https://brainfoolong.github.io/rcon-web-admin/images/logo.png
            forecastle.stakater.com/appName: "RCON Web Admin"
            forecastle.stakater.com/group: "yogs"
        websocketIngress:
          hostname: yogs-rwa-ws.mc.playhrzn.com
          annotations:
            kubernetes.io/ingress.class: "nginx"
      cloudCommander:
        enabled: true
        auth: false
        image: coderaiser/cloudcmd:14.6.0-alpine@sha256:f0fbdbac4058cf075988119a54965c1f822f01cd1082260fc5cb5eb4d6464f65
        serviceType: NodePort
        ingress:
          enabled: true
          hostname: yogs-files.mc.playhrzn.com
          annotations:
            ingress.pomerium.io/allowed_domains: '["chipwolf.uk", "hrznstudio.com"]'
            forecastle.stakater.com/expose: "true"
            forecastle.stakater.com/icon: https://cloudcmd.io/img/logo/cloudcmd.png
            forecastle.stakater.com/appName: "File Manager"
            forecastle.stakater.com/group: "yogs"
    extraEnv:
      GENERIC_PACK: "https://cdn.hrzn.studio/yogs-server-staging.zip"
      GENERIC_PACK_STRIP_DIRS: "0"
      OVERRIDE_SERVER_PROPERTIES: "1"
      USE_AIKAR_FLAGS: "1"
    persistence:
      dataDir:
        enabled: true
        Size: 5Gi
      storageClass: ebs-sc
      volumeName: pvc-d0d01d32-bf54-4339-8272-80190ecd186e
---
apiVersion: "autoscaling.k8s.io/v1beta2"
kind: VerticalPodAutoscaler
metadata:
  name: yogs-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: mc-yogs-minecraft
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 100m
          memory: 4608Mi
        maxAllowed:
          cpu: 2
          memory: 8Gi
        controlledResources: ["cpu", "memory"]
