apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: yogs
  namespace: mc
spec:
  chart:
    git: git@github.com:HRZNStudio/playhrzn-k8s
    ref: master
    path: charts/minecraft
  values:
    # ref: charts/minecraft/values.yaml
    resources:
      requests:
        memory: 8Gi
        cpu: "1"
    livenessProbe:
      initialDelaySeconds: 300
      periodSeconds: 10
    readinessProbe:
      initialDelaySeconds: 300
      periodSeconds: 10
    minecraftServer:
      eula: "TRUE"
      version: "1.12.2"
      type: "PAPER"
      forgeVersion: "14.23.5.2847"
      maxWorldSize: 29999984
      maxtickTime: -1
      memory: 8G
      annotations:
        external-dns.alpha.kubernetes.io/hostname: yogs.mc.playhrzn.com
      rcon:
        enabled: true
        serviceType: NodePort
      rconWebAdmin:
        enabled: true 
        image: docker.io/cwlf/rcon@sha256
        imageTag: e6d0d325f9686c00f8b4b50afd9ef7a03a5bf0c305e7567db008d8679163c6b1
        websocketUrlSsl: "wss://yogs-rwa.mc.playhrzn.com:4327"
        serviceType: NodePort
        ingress:
          enabled: true
          sslRedirect: true
          annotations:
            kubernetes.io/ingress.class: alb
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/group.name: yogs-rwa
            alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-2:521397258504:certificate/30948eb5-f96e-423d-8eec-cb26cb459de6
            external-dns.alpha.kubernetes.io/hostname: yogs-rwa.mc.playhrzn.com
          webAnnotations:
            alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}, {"HTTPS":443}]'
            alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
          websocketAnnotations:
            alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":4327}]'
      cloudCommander:
        enabled: true
        imageTag: 14.3.10-alpine
        serviceType: NodePort
        ingress:
          enabled: true
          sslRedirect: true
          annotations:
            kubernetes.io/ingress.class: alb
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}, {"HTTPS":443}]'
            alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
            alb.ingress.kubernetes.io/success-codes: '401'
            alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-2:521397258504:certificate/30948eb5-f96e-423d-8eec-cb26cb459de6
            external-dns.alpha.kubernetes.io/hostname: yogs-files.mc.playhrzn.com
    extraEnv:
      GENERIC_PACK: "https://cdn.hrzn.studio/yogs-server-staging.zip"
      GENERIC_PACK_STRIP_DIRS: "0"
      OVERRIDE_SERVER_PROPERTIES: "1"
    persistence:
      dataDir:
        enabled: true
        Size: 5Gi
      storageClass: ebs-sc
      #volumeName:
