---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fluxcloud
  namespace: flux
spec:
  encryptedData:
    slack_url: AgAI2IwPJhoXJwzLHSNom33oJ7aoOjIdBfDoFlamQHpqi8mcVMK+jFuHMZuS4utf7ympTK4Nx0i5Tixi6uJrCoP9USCuRTSn489ak9OlhwB6a/fcJ8mDo2Ob3WIKr990HHIZkmkdGEIn2F0lNErEOgDKczLv+e7YMrHwkO9fn7VtFhCNR0RK1mK9svJGX6glEyRgFQN08YGe0aL1fdUyExTLFerPtjLX2TtXBDOLcTXxvQRAL3hYWfM7dx3b1Eu+SKOHz0hVbQwJI1c3L9HiVSeOw68MaUIIeMsr8+mT1NgLqJzRioqBvwEwQhCJP8jFCP3fYcjCIkCvgVTHpUjOjM9fDwvfhmE+abk88C3TroRE1VhXen8pZx/+XZ4uLF5SokcOm4ThCulm+/ondsYSQXfZvlEMEYKtd1gFoLkaEM6Nn5FaBuik6wCWJq9YPpa0/9R5z1JwdvgZvL+ZWuae6gna/GvlWvr8uZ0Ng/3zbpNOE5n+SBSYrISgdABu5srZXfzWqAknFacrYmYy0SHlUxyYT6b4LF37PazrVjTeDIFNley/ld3LSzsHRettBkT/lrMZbV6gwuIF4+POlIRWUE9H4DGSmEAJVXveoRkADTMpVZsswb9dhll7Xc9wnDUFJWJi3nx+LD4mnFWT4WSIrDLRxXh/FD17JsxXyZCUSlw0yGR9s01mWUQBE/c7fLek72Ff+vAGQrAkabRfIgS9D5HpmK48br34i02vNs6tTxJzcLMfSWlI4Xra9VTsd5xQKYb+vHijGAN3C+hpFHQyiiiBCvNcT24LPTBa8q+5YsbL7+4=
  template:
    metadata:
      creationTimestamp: null
      name: fluxcloud
      namespace: flux
    type: Opaque
