---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghost
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ghost
      version: 12.1.2
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  valuesFrom:
  - kind: Secret
    name: ghost-helm-values
    optional: false
  values:
    ghostHost: blog.hacksm.net
    ghostProtocol: https
    ghostPort: 443
    ghostUsername: matt@matt-white.co.uk
    ghostEmail: matt@matt-white.co.uk
    ghostBlogTitle: HACKSM Blog
    service:
      type: ClusterIP
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/enable-global-auth: "false"
        nginx.ingress.kubernetes.io/proxy-body-size: "20m"
        nginx.org/client-max-body-size: "20m"
      hostname: blog.hacksm.net
      tls: true
    persistence: 
      enable: true
      existingClaim: cifs-data-pvc
      path: ghost
    mariadb:
      auth:
        rootPassword: "password"
        password: "password"
      primary:
        persistence:
          enabled: true
          existingClaim: cifs-data-pvc
          subPath: ghostdb
