---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
spec:
  releaseName: prometheus-operator
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: prometheus-operator
    version: 8.13.8
  values:
    grafana:
      enabled: true
      defaultDashboardsEnabled: true
      grafana.ini:
        users:
          viewers_can_edit: false
        auth:
          disable_login_form: true
          disable_signout_menu: true
        auth.anonymous:
          enabled: true
          org_role: Viewer
      ingress:
        enabled: true
        hosts: ["grafana.mc.playhrzn.com"]
        annotations:
          ingress.pomerium.io/allowed_domains: '["chipwolf.uk", "hrznstudio.com"]'
          nginx.ingress.kubernetes.io/auth-signin: https://forwardauth.mc.playhrzn.com/?uri=$scheme://$host$request_uri
          nginx.ingress.kubernetes.io/auth-url: https://forwardauth.mc.playhrzn.com/verify?uri=$scheme://$host$request_uri
          forecastle.stakater.com/expose: "true"
          forecastle.stakater.com/appName: Grafana
          forecastle.stakater.com/icon: https://raw.githubusercontent.com/stakater/ForecastleIcons/master/grafana.png
          external-dns.alpha.kubernetes.io/hostname: grafana.mc.playhrzn.com
    nodeExporter:
      serviceMonitor:
        relabelings:
          - sourceLabels: [__meta_kubernetes_pod_node_name]
            targetLabel: instance
