---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kibana
  namespace: elastic-stack
spec:
  releaseName: kibana
  chart:
    repository: https://helm.elastic.co
    name: kibana
    version: 7.7.0
  values:
    ingress:
      enabled: true
      hosts: ["kibana.mc.playhrzn.com"]
      annotations:
        ingress.pomerium.io/allowed_domains: '["chipwolf.uk", "hrznstudio.com"]'
        nginx.ingress.kubernetes.io/auth-signin: https://forwardauth.mc.playhrzn.com/?uri=$scheme://$host$request_uri
        nginx.ingress.kubernetes.io/auth-url: https://forwardauth.mc.playhrzn.com/verify?uri=$scheme://$host$request_uri
        external-dns.alpha.kubernetes.io/hostname: kibana.mc.playhrzn.com
        forecastle.stakater.com/expose: "true"
        forecastle.stakater.com/icon: https://github.com/stakater/ForecastleIcons/raw/master/kibana.png
        forecastle.stakater.com/appName: "Kibana"
        forecastle.stakater.com/group: "monitoring"
