---
apiVersion: v1
data:
  cluster.name: playhrzn-dev
  logs.region: eu-west-2
  # The below configuration file is in JSON format.
  # Please ensure you keep it well-formed if you modify it.
  cluster-info.json: |
    {
      "cluster": {
        "name": "playhrzn-dev"
      },
      "logs": {
        "region": "eu-west-2"
      }
    }
kind: ConfigMap
metadata:
  name: cluster-info
  namespace: amazon-cloudwatch
