---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: hacksm
  namespace: hacksm
spec:
  releaseName: hacksm
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: nginx
    version: 7.1.4
  values:   
    service:
      type: ClusterIP
    cloneStaticSiteFromGit:
      enabled: true
      repository: "https://github.com/krangence/hacksm.net.git"
      branch: "main"
    ingress: 
      enabled: true
      certManager: true
      annotations:
        forecastle.stakater.com/expose: "true"
        forecastle.stakater.com/appName: "hacksm.net"
        forecastle.stakater.com/icon: https://avatars1.githubusercontent.com/u/2178663
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/enable-global-auth: "false"
      hostname: "hacksm.net"
      tls: true
    