---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ghost
  namespace: nginx
spec:
  releaseName: nginx
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: nginx
    version: 7.1.3
cloneStaticSiteFromGit:
  enable: true
  repository: "www.github.com/hacksm.net"
containerPorts:
ingress: 
  enable: true
  certManager: true
  annotations:
        forecastle.stakater.com/expose: "true"
        forecastle.stakater.com/appName: "hacksm.net"
        forecastle.stakater.com/icon: https://avatars1.githubusercontent.com/u/2178663
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/enable-global-auth: "false"
  hosts:
    - hacksm.net
    - www.hacksm.net
    tls: true