---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  releaseName: home-assistant
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: home-assistant
    version: 2.5.0
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 0.117.5
    persistence:
      enabled: true
      size: 2Gi
      storageClass: "hcloud-volumes"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/enable-global-auth: "false"
      hosts:
      - hass.hacksm.net
    hostNetwork: true
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
    vscode:
      enabled: true
      service:
        port: 8085
      image:
        repository: codercom/code-server
        tag: 3.5.0
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          ingress.pomerium.io/allowed_users: '["matt@matt-white.co.uk", "hello@chipwolf.uk"]'
        hosts:
        - hass-vscode.hacksm.net
    resources:
      limits:
        memory: 2500Mi
      requests:
        cpu: 35m
        memory: 512Mi
    monitoring:
      enabled: false
    postgresql:
      enabled: true
      persistence:
        enabled: true
        storageClass: "hcloud-volumes"
