---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: csi-driver-smb
  namespace: kube-system
spec:
  releaseName: csi-driver-smb
  chart:
    git: git@github.com:kubernetes-csi/csi-driver-smb.git
    tag: 4f01661f9aac5211567699d667fb8ee6928cc6b1
    path: charts/latest/csi-driver-smb
