---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  releaseName: ingress-nginx
  chart:
    repository: https://kubernetes.github.io/ingress-nginx/
    name: ingress-nginx
    version: 3.3.0
  values:
    fullnameOverride: ingress-nginx
    controller:
      dnsPolicy: ClusterFirstWithHostNet
      reportNodeInternalIp: true
      hostNetwork: true
      hostPort:
        enabled: true
      service:
        targetPorts:
          http: tohttps
          https: http
      containerPort:
        http: 80
        https: 443
        tohttps: 2443
      config:
        global-auth-signin: https://forwardauth.hacksm.net/?uri=$scheme://$host$request_uri
        global-auth-url: https://forwardauth.hacksm.net/verify?uri=$scheme://$host$request_uri
        use-proxy-protocol: "false"
        proxy-real-ip-cidr: 192.168.0.0/16
        use-forwarded-headers: "true"
        ssl-redirect: "false"
        proxy-body-size: 32m
        http-snippet: |
          server {
            listen 2443 proxy_protocol;
            return 307 https://$host$request_uri;
          }
