---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: forecastle
  namespace: forecastle
spec:
  releaseName: forecastle
  chart:
    git: git@github.com:stakater/Forecastle.git
    ref: v1.0.41
    path: deployments/kubernetes/chart/forecastle
