---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hetzner-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: hcloud-volumes
