---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: code-server
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: code-server
      version: 0.1.4
      sourceRef:
        kind: HelmRepository
        name: nicolaswilde-charts
        namespace: flux-system
      interval: 5m
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
      hosts:
        - host: code.hacksm.net
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - code.hacksm.net
    persistence:
      config:
        enabled: true
        storageClass: hcloud-volumes
#    extraContainers:
#    - env:
#      - name: GIT_SYNC_REPO
#        value: https://github.com/krangence/code-wiki.git
#      - name: GIT_SYNC_DEST
#        value: git
#      - name: GIT_SYNC_WAIT
#        value: '10'
#      - name: GIT_SYNC_SSH
#        value: 'true'
#      - name: GIT_SSH_KEY_FILE
#        value: /var/ssh/sshkey
#      - name: GIT_SSH_KNOWN_HOSTS_FILE
#        value: /var/knownhosts/known_hosts
#      image: 'k8s.gcr.io/git-sync:v3.1.1'
#      name: git-sync
#      volumeMounts:
#      - mountPath: /var/ssh
#        name: ssh-key
#      - mountPath: /var/knownhosts
#        name: known-hosts
#      - mountPath: /home/coder
#        name: git-sync-volume
#    extraVolumeMounts:
#    - mountPath: /var/ssh
#      name: ssh-key
#      readOnly: true
#    - mountPath: /var/knownhosts
#      name: known-hosts
#      readOnly: true
#    - mountPath: /home/coder
#      name: git-sync-volume
#    extraVolumes:
#    - name: ssh-key
#      secret:
#        items:
#        - key: key
#          path: sshkey
#        secretName: dags-secret
#    - name: known-hosts
#      secret:
#        items:
#        - key: known_hosts
#          path: known_hosts
#        secretName: dags-secret
#    - emptyDir: {}
#      name: git-sync-volume
