helmOperator:
  create: false
git:
  url: "git@github.com:krangence/hacksm"
registry:
  rps: 50
  burst: 50
additionalArgs:
- --connect=ws://fluxcloud
syncGarbageCollection:
  enabled: true
  dry: false
