---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  releaseName: external-dns
  chart:
    git: https://github.com/bitnami/charts
    ref: master
    path: bitnami/external-dns
