{{- if .Values.minecraftServer.cloudCommander.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ template "minecraft.fullname" . }}-cloudcmd"
  {{- if .Values.minecraftServer.cloudCommander.ingress.annotations }}
  annotations:
    {{- range $key, $value := .Values.minecraftServer.cloudCommander.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  labels:
    app: {{ template "minecraft.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  rules:
  - http:
      paths:
      {{- if .Values.minecraftServer.rconWebAdmin.ingress.sslRedirect }}
      - path: /*
        backend:
          serviceName: ssl-redirect
          servicePort: use-annotation
      {{- end }}
      - path: /*
        backend:
          serviceName: "{{ template "minecraft.fullname" . }}-cloudcmd"
          servicePort: {{ .Values.minecraftServer.cloudCommander.port }}
{{- end -}}
