---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hetzner-data-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hcloud-volumes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hetzner-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: hcloud-volumes
