---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cifs-wiki-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  flexVolume:
    driver: juliohm/cifs
    options:
      server: u257377.your-storagebox.de
      share: /backup/wiki
    secretRef:
      name: cifs
      namespace: kube-system
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cifs-wiki-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
