---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wiki
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: wikijs
      version: 0.1.8
      sourceRef:
        kind: HelmRepository
        name: nicolaswilde-charts
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: "Europe/London"
    ingress: 
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/auth-url: "https://auth.hacksm.net/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: https://auth.hacksm.net/oauth2/start
      hosts: 
        - host: wiki.hacksm.net
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - wiki.hacksm.net
    persistence:
      config:
        enabled: true
        existingClaim: cifs-data-pvc
        mountPath: /wikijsconfig
      data:
        enabled: true
        existingClaim: cifs-data-pvc
        mountPath: /wikijsdata
        