---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pomerium
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: pomerium
      version: 15.0.0
      sourceRef:
        kind: HelmRepository
        name: pomerium-charts
        namespace: flux-system
      interval: 5m
  valuesFrom:
  - kind: Secret
    name: pomerium-helm-values
    optional: false
  values:
    ingress:
      annotations:
        kubernetes.io/ingress.class: "nginx"
        kubernetes.io/ingress.allow-http: "false"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        nginx.ingress.kubernetes.io/enable-global-auth: "false"
        nginx.ingress.kubernetes.io/proxy-buffer-size: "16K"
    forwardAuth:
      enabled: true
    service:
      type: NodePort
    config:
      rootDomain: hacksm.net
    operator:
      enabled: true
      config:
        ingressClass: nginx
