---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: minio
      version: 8.0.9
      sourceRef:
        kind: HelmRepository
        name: minio-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: jessestuart/minio
      tag: RELEASE.2020-08-08T04-50-06Z
    mcImage:
      repository: jessestuart/mc
      tag: RELEASE.2020-08-08T02-33-58Z
    helmKubectlJqImage:
      repository: drnic/kubectl
      tag: 1.16
    persistence:
      existingClaim: cifs-data-pvc
      subPath: minio
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/enable-global-auth: "false"
      hosts: [minio.hacksm.net]
      tls:
      - hosts:
        - minio.hacksm.net
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 1000Mi
    securityContext:
      enabled: false
    #metrics:
    #  serviceMonitor:
    #    enabled: true
    nasgateway:
      enabled: true
      # Number of parallel instances
      replicas: 1
  valuesFrom:
  - kind: Secret
    name: "minio-helm-values"
    optional: false
