---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: acme-crt
  namespace: kube-system
spec:
  secretName: acme-crt-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - hacksm.net
  - '*.hacksm.net'
  - matt-white.co.uk
  - '*.matt-white.co.uk'
  - nitetech.co.uk
  - '*.nitetech.co.uk'
